import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Chat from "@learning-game/components/chat/Chat";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Add the desired weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased relative`}>
        <Link
          href="/"
          className="absolute z-10 bg-blue-300 flex flex-row items-center justify-center top-10 right-10 size-12 border border-transparent rounded-full"
        >
          <Image
            src="/home.png"
            alt="home"
            width={500}
            height={500}
            className="size-9"
          />
        </Link>
        <Chat username="test" />
        {children}
      </body>
    </html>
  );
}
